### ISSUE TITLE
emacs is an issue?

### ISSUE THREAD

**Issue by solomondg** [bpsrobotics/bpsrobotics.github.io#3]
![wakemeup](https://cloud.githubusercontent.com/assets/695408/18282564/7dd606ec-7416-11e6-81b1-48ff676d0f6d.jpg)

**Comment by philiparola** [comment]
Inconsistent tabs and spacing, missing newline, mismatched linking conventions... oh my!

**Comment by solomondg** [comment]
```
wh  at? emacs.   is good if   you manually   in dent
```

**Comment by philiparola** [comment]
this will literally never be fixed why did i even try
